implemented check for platform to guarantee communication with bitbox
digitalbitbox/ElectronDemo pull request #3
Opened 2018-11-26 13:50 UTC by kaisert

Currently the implementation of communication.js will not work on windows platforms since bitbox does not react to any attempted sends. To guarantee this, it is necessary to first check for the platform this app is running on and if it is windows prepend a bit to the message. For further information see https://github.com/node-hid/node-hid#prepend-byte-to-hid_write

2018-11-26 14:19 UTC, thisconnect requested changes
thanks @kaisert please update package.json, and remove os from dependecies

2018-11-26 14:19 UTC, thisconnect commented on package.json
> +    "os": "^0.1.1",
`os` is a native nodejs module (https://nodejs.org/dist/latest-v10.x/docs/api/os.html), please remove as dependency

2018-11-26 15:01 UTC, thisconnect approved these changes
cc @stephaniestroka

2018-11-27 09:31 UTC, benma approved these changes

2018-11-27 09:37 UTC, merged

2018-11-27 09:38 UTC, benma commented
Thanks @kaisert!